# This file was generated by GoReleaser. DO NOT EDIT.
cask "updock" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0a7097de203a5579f0c71ac57874644442793d2dc833e2f9b54fb33301e9a041"
      url "https://github.com/amrelsagaei/updock/releases/download/v#{version}/updock_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "61b551f64003307b05abd459cec5b3a1f19e632ce3e4373e0625cebf16ff1b12"
      url "https://github.com/amrelsagaei/updock/releases/download/v#{version}/updock_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "90beebfc72f56b2905f3be26fc99d0b1eaacb7029a5f06557b498a2b44807fb3"
      url "https://github.com/amrelsagaei/updock/releases/download/v#{version}/updock_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "eb53fc08ebf2e10bb384d6abf225deadc18e4fdcac9aabb97929a3ee8f6559f0"
      url "https://github.com/amrelsagaei/updock/releases/download/v#{version}/updock_#{version}_linux_arm64.tar.gz"
    end
  end

  name "updock"
  desc "Run any Docker app from one word."
  homepage "https://amrelsagaei.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "updock"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/updock"]
    end
  end

  # No zap stanza required

end
