# This file was generated by GoReleaser. DO NOT EDIT.
cask "updock" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "ac6329d0535d2d8fd322321b8fe6057e62913b308dd6cf49dc266b660fa5ef11"
      url "https://github.com/amrelsagaei/updock/releases/download/v#{version}/updock_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ae98b907b59243adf28e2d32f4fd74f4176da33f707552163a26ed3ccad954c"
      url "https://github.com/amrelsagaei/updock/releases/download/v#{version}/updock_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4cb7157bc11cfbf18552fcccd64b537eb9a99967a13442ccc31f6d1d74235ae"
      url "https://github.com/amrelsagaei/updock/releases/download/v#{version}/updock_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d0478c3eef79592bf474e13cf7ab7733c85913dcc5b4b4a1fc8f274c098c325"
      url "https://github.com/amrelsagaei/updock/releases/download/v#{version}/updock_#{version}_linux_arm64.tar.gz"
    end
  end

  name "updock"
  desc "Run any Docker app from one word."
  homepage "https://amrelsagaei.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "updock"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/updock"]
    end
  end

  # No zap stanza required

end
