# This file was generated by GoReleaser. DO NOT EDIT.
cask "updock" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "9a3c0b1a3f7b63dac32d8db4a655af3130d4593347e17da283898f1dfc1691ef"
      url "https://github.com/amrelsagaei/updock/releases/download/v#{version}/updock_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a6857d2b8f787cc00f802abbe5c3f7e2c2bb8c85a36af46994bb3b742d64ded"
      url "https://github.com/amrelsagaei/updock/releases/download/v#{version}/updock_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "81d2e2e92ed4d6f04a071a306f519558f963c7230a303972b701e3d087597cc5"
      url "https://github.com/amrelsagaei/updock/releases/download/v#{version}/updock_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "c0b864975627d29f13e11732a425424358bfb6848011ca249d638dc72665fc37"
      url "https://github.com/amrelsagaei/updock/releases/download/v#{version}/updock_#{version}_linux_arm64.tar.gz"
    end
  end

  name "updock"
  desc "Run any Docker app from one word."
  homepage "https://amrelsagaei.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "updock"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/updock"]
    end
  end

  # No zap stanza required

end
